### ISSUE TITLE
Couldn't find package "@alorel/rollup-plugin-web-worker" on the "npm" registry.

### ISSUE THREAD

**Issue by yovanoc** [Alorel/rollup-plugin-web-worker#3]
I put the .npmrc and try to install but nothing work, too bad :/

**Comment by Alorel** [comment]
It works fine on my end. [Read the install instructions](https://github.com/Alorel/rollup-plugin-web-worker#installation) and make sure you're authenticated with Github since their package registry doesn't seem to allow unauthenticated requests for some reason..

```
art@art-oobster-reinstalled:~/Downloads/npmrc-test$ cat ./.npmrc
@alorel:registry=https://npm.pkg.github.com
art@art-oobster-reinstalled:~/Downloads/npmrc-test$ npm init -y
Wrote to /home/art/Downloads/npmrc-test/package.json:

{
  "name": "npmrc-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


art@art-oobster-reinstalled:~/Downloads/npmrc-test$ npm install @alorel/rollup-plugin-web-worker
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @alorel/rollup-plugin-web-worker@1.0.2 requires a peer of rollup@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN npmrc-test@1.0.0 No description
npm WARN npmrc-test@1.0.0 No repository field.

+ @alorel/rollup-plugin-web-worker@1.0.2
added 5 packages from 4 contributors and audited 5 packages in 1.012s
found 0 vulnerabilities

art@art-oobster-reinstalled:~/Downloads/npmrc-test$
```

EDIT: sorry, I hit "send" prematurely there.

**Comment by yovanoc** [comment]
Maybe because I'm using yarn, I will investigate further so, but are you sure that you not have access because you are the owner?..

**Comment by Alorel** [comment]
Hm, I don't _think_ so? If you're able to access the [package page](https://github.com/Alorel/rollup-plugin-web-worker/packages/411484) you should have the rights to install it and, if it was a permission issue, iirc you should get an "unauthorised" message instead of a "not found" one. I just double-checked the library's package.json in node_modules and it's set to public:

```json
  "publishConfig": {
    "access": "public",
    "registry": "https://npm.pkg.github.com"
  },
```

This repo is using yarn as well (albeit the v2.x beta); I'm not sure about the yarnrc syntax for v1.x - yarn doesn't use npmrc iirc, but you can try copying over the `.yarn` directory and `.yarnrc.yml` to your project and seeing if that works (though I think you might have to remove other npmrc/yarnrc configs first)?

If you start getting unauthorised error messages and haven't installed anything from the github package registry before, you might need to do a one time setup on your machine, there are instructions available [here](https://docs.github.com/en/free-pro-team@latest/packages/guides/configuring-npm-for-use-with-github-packages).

**Comment by yovanoc** [comment]
It's working, my bad
